options:
   openstack-origin:
        default: distro
        type: string
        description: |
          Repository from which to install.  May be one of the following:
          distro (default), ppa:somecustom/ppa, a deb url sources entry,
          or a supported Cloud Archive release pocket.

          Supported Cloud Archive sources include: cloud:precise-folsom,
          cloud:precise-folsom/updates, cloud:precise-folsom/staging,
          cloud:precise-folsom/proposed.

          Note that updating this setting to a source that is known to
          provide a later version of OpenStack will trigger a software
          upgrade.
   webroot:
        default: "/horizon"
        type: string
        description: |
            Directory where application will be accessible, relative to
            http://$hostname/.
   default-role:
        default: "Member"
        type: string
        description: |
            Default role for Horizon operations that will be created in
            Keystone upon introduction of an identity-service relation.
    # HA configuration settings
    vip:
        type: string
        description: "Virtual IP to use to front openstack dashboard ha configuration"
    vip_iface:
        type: string
        default: eth0
        description: "Network Interface where to place the Virtual IP"
    vip_cidr:
        type: int
        default: 24
        description: "Netmask that will be used for the Virtual IP"
    ha-bindiface:
        type: string
        default: eth0
        description: |
          Default network interface on which HA cluster will bind to communication
          with the other members of the HA Cluster.
    ha-mcastport:
        type: int
        default: 5410
        description: |
          Default multicast port number that will be used to communicate between
          HA Cluster nodes.
